services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
